#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pocket-id"
name = "Pocket-ID"
description.en = "Easy-to-use OIDC provider that allows users to authenticate with their passkeys to your services"
description.fr = "Fournisseur OIDC simple qui permet aux utilisateurs de s'authentifier auprès de vos services à l'aide de leurs clés d'accès"

version = "2.4.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "BSD-2-Clause"
website = "https://pocket-id.org/"
demo = "https://demo.pocket-id.org/"
admindoc = "https://pocket-id.org/docs"
code = "https://github.com/pocket-id/pocket-id"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "pocket-id"
    in_subdir = false
    extract = false
    amd64.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.4.0/pocket-id-linux-amd64"
    amd64.sha256 = "e21fe89b81ec5219c1fb21c3a82acc6942fea93962b7d57a4307517f149f1149"
    arm64.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.4.0/pocket-id-linux-arm64"
    arm64.sha256 = "93dad2a96b010499909f47c00b2744f0b72e5af4b733994ac43b8223bd587fd3"
    armhf.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.4.0/pocket-id-linux-armv7"
    armhf.sha256 = "22d35835beaf9b562de47ccdfe0c2bed5d545640def4e817d37ad092999103fd"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^pocket-id-linux-amd64$"
    autoupdate.asset.arm64 = "^pocket-id-linux-arm64$"
    autoupdate.asset.armhf = "^pocket-id-linux-armv7$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
