#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pocket-id"
name = "Pocket-ID"
description.en = "Easy-to-use OIDC provider that allows users to authenticate with their passkeys to your services"
description.fr = "Fournisseur OIDC simple qui permet aux utilisateurs de s'authentifier auprès de vos services à l'aide de leurs clés d'accès"

version = "2.16.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "BSD-2-Clause"
website = "https://pocket-id.org/"
demo = "https://demo.pocket-id.org/"
admindoc = "https://pocket-id.org/docs"
code = "https://github.com/pocket-id/pocket-id"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "pocket-id"
    in_subdir = false
    extract = false
    amd64.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.16.0/pocket-id_linux_amd64"
    amd64.sha256 = "4ba26810e8d2c2d46aea42d8e960cb457cf8bc36cc009446a18d7d856abd3aa7"
    arm64.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.16.0/pocket-id_linux_arm64"
    arm64.sha256 = "b27adab8f84262b6903d7ff21247c22b11fa318dd16e81b8aafdc84bac823003"
    armhf.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.16.0/pocket-id_linux_armv7"
    armhf.sha256 = "9265f00165ba9be83c847c5298e56a21a492a6cfd86ccd51f3cf8c3e78f97717"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^pocket-id_linux_amd64$"
    autoupdate.asset.arm64 = "^pocket-id_linux_arm64$"
    autoupdate.asset.armhf = "^pocket-id_linux_armv7$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
