#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pocket-id"
name = "Pocket-ID"
description.en = "Easy-to-use OIDC provider that allows users to authenticate with their passkeys to your services"
description.fr = "Fournisseur OIDC simple qui permet aux utilisateurs de s'authentifier auprès de vos services à l'aide de leurs clés d'accès"

version = "2.6.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "BSD-2-Clause"
website = "https://pocket-id.org/"
demo = "https://demo.pocket-id.org/"
admindoc = "https://pocket-id.org/docs"
code = "https://github.com/pocket-id/pocket-id"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    rename = "pocket-id"
    in_subdir = false
    extract = false
    amd64.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.6.2/pocket-id-linux-amd64"
    amd64.sha256 = "348c2cfb6457d31078327c203896c29509d0417982c78bfac185d07859dc5b86"
    arm64.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.6.2/pocket-id-linux-arm64"
    arm64.sha256 = "acbb91b611236d5277c85497dd1fa48140cfaa1a51da11219fa480e8e9141472"
    armhf.url = "https://github.com/pocket-id/pocket-id/releases/download/v2.6.2/pocket-id-linux-armv7"
    armhf.sha256 = "94fa9459f1be6a304d9c96b13404f7df69f27d32d3a2433d033457bdf1e128db"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^pocket-id-linux-amd64$"
    autoupdate.asset.arm64 = "^pocket-id-linux-arm64$"
    autoupdate.asset.armhf = "^pocket-id-linux-armv7$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"
